for f in $SPARK_HOME/jars/*.jar; do
  if [ "$SPARK_CLASSPATH" ]; then
    export SPARK_CLASSPATH=$SPARK_CLASSPATH:$f
  else
    export SPARK_CLASSPATH=$f
  fi
done

export HADOOP_CLASSPATH=$SPARK_CLASSPATH
export SPARK_DIST_CLASSPATH=$SPARK_CLASSPATH
