#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG SPARK_IMAGE=gcr.io/mapr-hpe/spark-2.4.4:201912180140
FROM ${SPARK_IMAGE}

## Setup dependencies for Google Cloud Storage access.
#RUN rm $SPARK_HOME/jars/guava-14.0.1.jar
ADD https://repo1.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar $SPARK_HOME/jars

## Add the connector jar needed to access Google Cloud Storage using the Hadoop FileSystem API.
#ADD https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-latest-hadoop2.jar $SPARK_HOME/jars
#ADD https://storage.googleapis.com/spark-lib/bigquery/spark-bigquery-latest.jar $SPARK_HOME/jars

# Remove log4j 1.2 jars
RUN rm -f $HADOOP_HOME/share/hadoop/common/lib/log4j-1.2* \
   && rm $HADOOP_HOME/share/hadoop/common/lib/slf4j-api-1.7* \
   && rm $HADOOP_HOME/share/hadoop/common/lib/slf4j-log4j12*

COPY jars/appender-core-2.6.0.jar $SPARK_HOME/jars
COPY jars/log4j-api-2.13.3.jar $SPARK_HOME/jars
COPY jars/log4j-api-scala_2.13-12.0.jar $SPARK_HOME/jars
COPY jars/log4j-core-2.13.3.jar $SPARK_HOME/jars
COPY jars/log4j-slf4j-impl-2.13.3.jar $SPARK_HOME/jars
COPY jars/log4js3-1.0.0.jar $SPARK_HOME/jars
COPY jars/slf4j-api-1.7.25.jar $SPARK_HOME/jars
# Add log4j 1.2 compatibility
ADD https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-1.2-api/2.13.3/log4j-1.2-api-2.13.3.jar $SPARK_HOME/jars

## Add Minio jars
ADD https://repo1.maven.org/maven2/io/minio/minio/7.0.2/minio-7.0.2.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/github/spotbugs/spotbugs-annotations/4.0.0/spotbugs-annotations-4.0.0.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.13.1/okhttp-3.13.1.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/squareup/okio/okio/1.17.2/okio-1.17.2.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/org/simpleframework/simple-xml/2.7.1/simple-xml-2.7.1.jar $SPARK_HOME/jars


   
 
