name: Docker Image HPE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile_hpe --tag sandhujag/hpespark:2.4.4
      working-directory: spark-hadoop-docker
      
    - name: Docker push
      run: docker push sandhujag/hpespark:2.4.4
      working-directory: spark-hadoop-docker
