name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login --username=yourhubusername --password=yourpassword
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sandhujag/s3spark:2.4.5
      working-directory: spark-hadoop-docker
      
    - name: Docker push
      run: docker push sandhujag/s3spark:2.4.5
      working-directory: spark-hadoop-docker
